<?php

/**
 * @file lingotek.module
 * 
 * Implements Drupal-related hooks for the Lingotek Translation module.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_permission().
 */
function lingotek_permission() {
  return array(
    'administer lingotek' => array(
      'title' => t('Administer Lingotek'),
      'description' => t('Access the administrative settings for the module.')
    ),
    'translation' => array(
      'title' => t('Translate'),
      'description' => t('Access to the translate content (e.g., the "Translations" tab will be available on nodes, comments will be translatable)')
    ),
    'manage projects' => array(
      'title' => t('Project Management'),
      'description' => t('Access the Lingotek tab on content types (Must also have permission to edit the content type in question).')
    ),
    'use lingotek developer tools' => array(
      'title' => t('Developer'),
      'description' => t('Access developer tools useful for detailed information and debugging')
    ),
  );
}

/**
 * Implements hook_toolbar().
 */
function lingotek_toolbar() {
  $items = array();
  $items['translation'] = array(
    '#type' => 'toolbar_item',
    '#attached' => array(
      'library' => array(
        'lingotek/lingotek.icons',
      ),
    ),
  );
  return $items;
}

/**
 * Implements hook_entity_create().
 */
function lingotek_entity_create(EntityInterface $entity) {
  // Only act on content entities.
  if (!($entity instanceof ContentEntityInterface)) {
    return;
  }
}

/**
 * Implements hook_entity_update().
 */
function lingotek_entity_update(EntityInterface $entity) {
  // Only act on content entities.
  if (!($entity instanceof ContentEntityInterface)) {
    return;
  }
}

/**
 * Implements hook_entity_delete().
 */
function lingotek_entity_delete(EntityInterface $entity) {
  // Only act on content entities.
  if (!($entity instanceof ContentEntityInterface)) {
    return;
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function lingotek_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // TODO: add profile info and etc. to the node form.
}

/**
 * Iplements hook_contextual_links_view_alter
 */
function lingotek_contextual_links_view_alter(&$element, $items) {
  // TODO
}
