lingotek.settings:
  type: config_object
  label: 'Lingotek settings'
  mapping:
    default:
      type: mapping
      label: 'Default'
      mapping:
        community:
          type: string
        project:
          type: string
        workflow:
          type: string
        vault:
          type: string
    preference:
      type: mapping
      label: 'Preference'
      mapping:
        advanced_parsing:
          type: boolean
        advanced_taxonomy_terms:
          type: boolean
        always_show_translate_tabs:
          type: boolean
        delete_tms_documents_upon_disassociation:
          type: boolean
        show_language_labels:
          type: boolean
        allow_local_editing:
          type: boolean
        language_specific_profiles:
          type: boolean

    account:
      type: mapping
      label: 'Account'
      mapping:
        use_production:
          type: boolean
          label: 'Use production'
        sandbox_host:
          type: string
          label: 'Sandbox Host'
        host:
          type: string
          label: 'Lingotek Host'
        authorize_path:
          type: string
        default_client_id:
          type: string
        plan_type:
          type: string
        resources:
          type: mapping
          label: 'Resources'
          mapping:
            community:
              type: sequence
              sequence:
                type: string
            project:
              type: sequence
              sequence:
                type: string
            workflow:
              type: sequence
              sequence:
                type: string
            vault:
              type: sequence
              sequence:
                type: string
        access_token:
          type: string
        login_id:
          type: string
        callback_url:
          type: string
    translate:
      type: mapping
      label: 'Translate'
      mapping:
        entity:
            type: sequence
            sequence:
              type: sequence
              sequence:
                type: ignore
        config:
            type: sequence
            sequence:
              type: sequence
              sequence:
                type: ignore
        interface:
            type: sequence
            sequence:
              type: sequence
              sequence:
                type: ignore
    field:
      type: string
    profile:
      type: sequence
      label: 'Profiles'
      sequence:
        type: lingotek.profile.[%key]

lingotek.profile.*:
  type: config_entity
  label: 'Lingotek Profile'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: 'Weight'
    locked:
      type: boolean
      label: 'Locked'
    auto_upload:
      type: boolean
      label: 'Automatic Upload'
    auto_download:
      type: boolean
      label: 'Automatic Download'
    vault:
      type: string
      label: 'TM Vault'
    project:
      type: string
      label: 'TM Project'
    workflow:
      type: string
      label: 'TM Workflow'
    language_overrides:
      type: sequence
      label: 'Target language settings overrides'
      sequence:
        type: mapping
        mapping:
          overrides:
            type: string
          custom:
            type: mapping
            mapping:
              workflow:
                type: string
                label: 'TM Workflow'
              auto_download:
                type: boolean
                label: 'Automatic Download'

lingotek.lingotek_config_metadata.*:
  type: config_entity
  label: 'Lingotek Config Metadata'
  mapping:
    config_name:
      type: string
      label: 'Config name'
    document_id:
      type: string
      label: 'Lingotek document id'
    source_status:
      type: sequence
      sequence:
        type: string
    target_status:
      type: sequence
      sequence:
        type: string
    hash:
      type: string
      label: 'Lingotek hash'

language.entity.*.third_party.lingotek:
  type: mapping
  label: 'Lingotek locale mapping'
  mapping:
    locale:
      type: string
      label: 'Lingotek locale code'
